repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: black
        language: system
        types: [ python ]
        files: ^(?:src|test)/.*\.py$
        pass_filenames: true
        stages: [ commit ]
        
  - repo: local
    hooks:
      - id: pytest
        name: Pytest
        entry: pytest
        language: system
        types: [ python ]
        pass_filenames: false
        verbose: true
        stages: [ push ]